-- MySQL Script generated by MySQL Workbench
-- Fri Sep  9 18:11:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restourant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restourant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restourant` DEFAULT CHARACTER SET utf8 ;
USE `restourant` ;

-- -----------------------------------------------------
-- Table `restourant`.`Ownerr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restourant`.`Ownerr` (
  `ownerr_id` INT NOT NULL AUTO_INCREMENT,
  `owner_firstname` VARCHAR(45) NULL,
  `owner_lastname` VARCHAR(45) NULL,
  `owner_birthdate` DATE NULL,
  PRIMARY KEY (`ownerr_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restourant`.`Administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restourant`.`Administrator` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `admin_firstname` VARCHAR(45) NULL,
  `admin_lastname` VARCHAR(45) NULL,
  `phone` VARCHAR(12) NULL,
  `salary` FLOAT NULL,
  `Ownerr_ownerr_id` INT NOT NULL,
  PRIMARY KEY (`admin_id`),
  INDEX `fk_Administrator_Ownerr1_idx` (`Ownerr_ownerr_id` ASC) VISIBLE,
  CONSTRAINT `fk_Administrator_Ownerr1`
    FOREIGN KEY (`Ownerr_ownerr_id`)
    REFERENCES `restourant`.`Ownerr` (`ownerr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restourant`.`Waiter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restourant`.`Waiter` (
  `waiter_id` INT NOT NULL AUTO_INCREMENT,
  `waiter_firstname` VARCHAR(45) NULL,
  `waiter_surname` VARCHAR(45) NULL,
  `salary` FLOAT NULL,
  `phone` INT(12) NULL,
  `Administrator_admin_id` INT NOT NULL,
  PRIMARY KEY (`waiter_id`),
  INDEX `fk_Waiter_Administrator1_idx` (`Administrator_admin_id` ASC) VISIBLE,
  CONSTRAINT `fk_Waiter_Administrator1`
    FOREIGN KEY (`Administrator_admin_id`)
    REFERENCES `restourant`.`Administrator` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restourant`.`Chef`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restourant`.`Chef` (
  `chef_id` INT NOT NULL AUTO_INCREMENT,
  `salary` FLOAT NULL,
  `chef_firstname` VARCHAR(45) NULL,
  `chef_lastname` VARCHAR(45) NULL,
  `Administrator_admin_id` INT NOT NULL,
  PRIMARY KEY (`chef_id`),
  INDEX `fk_Chef_Administrator1_idx` (`Administrator_admin_id` ASC) VISIBLE,
  CONSTRAINT `fk_Chef_Administrator1`
    FOREIGN KEY (`Administrator_admin_id`)
    REFERENCES `restourant`.`Administrator` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restourant`.`Ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restourant`.`Ingredients` (
  `ingredient_id` INT NOT NULL AUTO_INCREMENT,
  `ingredient_name` VARCHAR(45) NULL,
  PRIMARY KEY (`ingredient_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restourant`.`Meal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restourant`.`Meal` (
  `meal_id` INT NOT NULL AUTO_INCREMENT,
  `meal_name` VARCHAR(45) NOT NULL,
  `meal_price` VARCHAR(45) NOT NULL,
  `Chef_chef_id` INT NOT NULL,
  `Ingredients_ingredient_id` INT NOT NULL,
  PRIMARY KEY (`meal_id`, `meal_name`, `meal_price`),
  INDEX `fk_Meal_Chef1_idx` (`Chef_chef_id` ASC) VISIBLE,
  INDEX `fk_Meal_Ingredients1_idx` (`Ingredients_ingredient_id` ASC) VISIBLE,
  CONSTRAINT `fk_Meal_Chef1`
    FOREIGN KEY (`Chef_chef_id`)
    REFERENCES `restourant`.`Chef` (`chef_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Meal_Ingredients1`
    FOREIGN KEY (`Ingredients_ingredient_id`)
    REFERENCES `restourant`.`Ingredients` (`ingredient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restourant`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restourant`.`Menu` (
  `menu_id` INT NOT NULL AUTO_INCREMENT,
  `Administrator_admin_id` INT NOT NULL,
  `Meal_meal_id` INT NOT NULL,
  `Meal_meal_name` VARCHAR(45) NOT NULL,
  `Meal_meal_price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`menu_id`, `Meal_meal_id`, `Meal_meal_name`, `Meal_meal_price`),
  INDEX `fk_Menu_Administrator1_idx` (`Administrator_admin_id` ASC) VISIBLE,
  INDEX `fk_Menu_Meal1_idx` (`Meal_meal_id` ASC, `Meal_meal_name` ASC, `Meal_meal_price` ASC) VISIBLE,
  CONSTRAINT `fk_Menu_Administrator1`
    FOREIGN KEY (`Administrator_admin_id`)
    REFERENCES `restourant`.`Administrator` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Menu_Meal1`
    FOREIGN KEY (`Meal_meal_id` , `Meal_meal_name` , `Meal_meal_price`)
    REFERENCES `restourant`.`Meal` (`meal_id` , `meal_name` , `meal_price`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restourant`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restourant`.`Customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `customer_firstname` VARCHAR(45) NULL,
  `customer_lastname` VARCHAR(45) NULL,
  `phone` INT(12) NULL,
  `email` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  `Waiter_waiter_id` INT NOT NULL,
  `Menu_menu_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `fk_Customers_Waiter1_idx` (`Waiter_waiter_id` ASC) VISIBLE,
  INDEX `fk_Customers_Menu1_idx` (`Menu_menu_id` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_Waiter1`
    FOREIGN KEY (`Waiter_waiter_id`)
    REFERENCES `restourant`.`Waiter` (`waiter_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customers_Menu1`
    FOREIGN KEY (`Menu_menu_id`)
    REFERENCES `restourant`.`Menu` (`menu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restourant`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restourant`.`Orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `Waiter_waiter_id` INT NOT NULL,
  `Menu_menu_id` INT NOT NULL,
  `Menu_Meal_meal_id` INT NOT NULL,
  `Menu_Meal_meal_name` VARCHAR(45) NOT NULL,
  `Menu_Meal_meal_price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`order_id`, `Menu_menu_id`, `Menu_Meal_meal_id`, `Menu_Meal_meal_name`, `Menu_Meal_meal_price`),
  INDEX `fk_Orders_Waiter1_idx` (`Waiter_waiter_id` ASC) VISIBLE,
  INDEX `fk_Orders_Menu1_idx` (`Menu_menu_id` ASC, `Menu_Meal_meal_id` ASC, `Menu_Meal_meal_name` ASC, `Menu_Meal_meal_price` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Waiter1`
    FOREIGN KEY (`Waiter_waiter_id`)
    REFERENCES `restourant`.`Waiter` (`waiter_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Menu1`
    FOREIGN KEY (`Menu_menu_id` , `Menu_Meal_meal_id` , `Menu_Meal_meal_name` , `Menu_Meal_meal_price`)
    REFERENCES `restourant`.`Menu` (`menu_id` , `Meal_meal_id` , `Meal_meal_name` , `Meal_meal_price`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restourant`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restourant`.`Supplier` (
  `supplier_id` INT NOT NULL AUTO_INCREMENT,
  `supplier_name` VARCHAR(45) NULL,
  `supplier_city` VARCHAR(45) NULL,
  `phone` INT(12) NULL,
  `Administrator_admin_id` INT NOT NULL,
  PRIMARY KEY (`supplier_id`),
  INDEX `fk_Supplier_Administrator1_idx` (`Administrator_admin_id` ASC) VISIBLE,
  CONSTRAINT `fk_Supplier_Administrator1`
    FOREIGN KEY (`Administrator_admin_id`)
    REFERENCES `restourant`.`Administrator` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restourant`.`Supplier_Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restourant`.`Supplier_Address` (
  `supplier_adress` VARCHAR(45) NULL,
  `Supplier_supplier_id` INT NOT NULL,
  INDEX `fk_Supplier_Address_Supplier1_idx` (`Supplier_supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_Supplier_Address_Supplier1`
    FOREIGN KEY (`Supplier_supplier_id`)
    REFERENCES `restourant`.`Supplier` (`supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restourant`.`Ingredients_has_Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restourant`.`Ingredients_has_Supplier` (
  `Ingredients_ingredient_id` INT NOT NULL,
  `Supplier_supplier_id` INT NOT NULL,
  PRIMARY KEY (`Ingredients_ingredient_id`, `Supplier_supplier_id`),
  INDEX `fk_Ingredients_has_Supplier_Supplier1_idx` (`Supplier_supplier_id` ASC) VISIBLE,
  INDEX `fk_Ingredients_has_Supplier_Ingredients1_idx` (`Ingredients_ingredient_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ingredients_has_Supplier_Ingredients1`
    FOREIGN KEY (`Ingredients_ingredient_id`)
    REFERENCES `restourant`.`Ingredients` (`ingredient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingredients_has_Supplier_Supplier1`
    FOREIGN KEY (`Supplier_supplier_id`)
    REFERENCES `restourant`.`Supplier` (`supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restourant`.`Customers_has_Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restourant`.`Customers_has_Orders` (
  `Customers_customer_id` INT NOT NULL,
  `Orders_order_id` INT NOT NULL,
  PRIMARY KEY (`Customers_customer_id`, `Orders_order_id`),
  INDEX `fk_Customers_has_Orders_Orders1_idx` (`Orders_order_id` ASC) VISIBLE,
  INDEX `fk_Customers_has_Orders_Customers1_idx` (`Customers_customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_has_Orders_Customers1`
    FOREIGN KEY (`Customers_customer_id`)
    REFERENCES `restourant`.`Customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customers_has_Orders_Orders1`
    FOREIGN KEY (`Orders_order_id`)
    REFERENCES `restourant`.`Orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
